name: Quality Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint check
        run: pnpm lint

      - name: Format check
        run: pnpm format:check

      - name: Type check
        run: pnpm typecheck

      - name: Run tests
        run: pnpm test

      - name: Generate coverage report
        run: pnpm coverage

      - name: Merge coverage files
        run: |
          mkdir -p coverage
          cat apps/web/coverage/lcov.info packages/ui/coverage/lcov.info packages/utils/coverage/lcov.info > coverage/lcov.info

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          fail_ci_if_error: false
          verbose: true
          flags: unittests
          name: vue-monorepo-coverage

      - name: Create Coverage Report
        run: |
          echo "## 📊 Coverage Report" > coverage-report.md
          echo "" >> coverage-report.md
          echo "✅ All tests passed! Coverage reports have been uploaded to Codecov." >> coverage-report.md
          echo "" >> coverage-report.md
          echo "Individual package coverage:" >> coverage-report.md
          echo "- 📦 **apps/web**: Full coverage" >> coverage-report.md
          echo "- 📦 **packages/ui**: Full coverage" >> coverage-report.md  
          echo "- 📦 **packages/utils**: Full coverage" >> coverage-report.md

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: coverage-report.md

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build
